version: 0.2

phases:
  install:
    commands:
      - echo entered build phase
      - mvn clean package
  build:
    commands:
      - echo build completed successfully
artifacts:
  files:
    - target/spring-apigateway-example-0.0.1-SNAPSHOT.jar
  discard-paths: yes